### ISSUE TITLE
# MVPS:

### ISSUE THREAD

**Issue by moodln** [johnda911/ResTable#2]
- [x]  Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the MVP List or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of     feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
- [x] MVPs are listed in an ordered list
- [x] Each MVP is broken down into bullet points

**Comment by moodln** [comment]
- [ ] Each MVP should have two hashtags in front of them for correct formatting EX: ("## 1. Hosting on Heroku" becomes ==>)
## 1. Hosting on Heroku

**Comment by johnda911** [comment]
Hey Maddie, thank you again for all your comments. I have corrected all 5 issues(MVPs, backend routes, frontend routes, schema, sample state) you brought up in the comments(all showing under "In progress" tab now). It would be great if you could review them:) tomorrow!
